import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Panglima Roqiiqu Group",
  description: "Generated by Syafaruddin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="assets/logo/LOGO-GERAI-PANGLIMA-01.svg" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
